export const ACCESS_TOKEN_SECRET = 'HELLO, ACCESS_TOKEN'
export const REFRESH_TOKEN_SECRET = 'GOOD AFTERNOON, REFRESH_TOKEN'
export const ACCESS_TOKEN_EXPIRES_IN = '10s'
export const REFRESH_TOKEN_EXPIRES_IN = '14d'
